// ghostty-sys — raw FFI to libghostty (`vendor/ghostty/include/ghostty.h`).
//
// Bindings are generated by `build.rs` via `bindgen` and written to
// `$OUT_DIR/bindings.rs`. Everything is `unsafe`. macOS-only — on other
// targets `build.rs` writes an empty bindings file so this crate still
// compiles for cross-builds (it just exposes no symbols).
//
// The `ghostty_*` namespace closely mirrors the C header. See `vendor/
// ghostty/macos/Sources/Ghostty/Ghostty.App.swift` for an authoritative
// usage example of the same API in Swift.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

#[cfg(target_os = "macos")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(not(target_os = "macos"))]
compile_error!("ghostty-sys is currently macOS-only. \
                The libghostty embedding API does not yet support other platforms.");
