//! Native filesystem watches for the file-tree based tools.
//!
//! The frontend renders snapshots returned by the existing discovery
//! commands. This module owns recursive OS watchers for those roots and emits
//! one debounced, tool-scoped event when a snapshot may have changed.

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::sync::mpsc::{self, Receiver, RecvTimeoutError, Sender};
use std::sync::Arc;
use std::time::{Duration, Instant};

use notify::event::ModifyKind;
use notify::{Config, Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use serde::Serialize;
use tauri::{AppHandle, Emitter};

/// Event emitted after native filesystem changes have settled briefly.
pub const FILE_TREE_CHANGED_EVENT: &str = "file-tree:changed";

const DEBOUNCE_WINDOW: Duration = Duration::from_millis(75);

/// Identifies which explorer owns a watched root.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum WatchScope {
    /// HTTP runner project tree.
    Http,
    /// Database explorer SQL workspace tree.
    Sql,
    /// Markdown vault tree.
    Markdown,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct FileTreeChanged {
    scope: WatchScope,
    paths: Vec<String>,
}

#[derive(Debug)]
struct WatchChange {
    scope: WatchScope,
    paths: Vec<PathBuf>,
}

/// Owns the native watchers for every file-tree root.
///
/// Watchers are keyed by `(scope, root)`, which allows the same directory to
/// be open in multiple tools without coupling their project lists.
pub struct FileTreeWatcher {
    watchers: parking_lot::Mutex<HashMap<(WatchScope, PathBuf), RecommendedWatcher>>,
    changed_tx: Sender<WatchChange>,
    internal_writes: Arc<parking_lot::Mutex<HashMap<PathBuf, Instant>>>,
}

impl FileTreeWatcher {
    /// Create the registry and its background event-coalescing worker.
    pub fn new(app: AppHandle) -> Self {
        let (changed_tx, changed_rx) = mpsc::channel();
        let internal_writes = Arc::new(parking_lot::Mutex::new(HashMap::new()));
        std::thread::Builder::new()
            .name("file-tree-watcher-dispatch".into())
            .spawn(move || dispatch_changes(app, changed_rx))
            .expect("spawn file-tree watcher dispatch thread");

        Self {
            watchers: parking_lot::Mutex::new(HashMap::new()),
            changed_tx,
            internal_writes,
        }
    }

    /// Ignore content events generated by an imminent in-app save. Native
    /// watchers cannot otherwise distinguish our write from another editor.
    pub fn mark_internal_write(&self, path: &std::path::Path) {
        let path = dunce::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
        self.internal_writes.lock().insert(path, Instant::now());
    }

    /// Make the watched roots for `scope` exactly match `roots`.
    ///
    /// Missing roots are skipped. Existing registrations are retained so a
    /// discovery refresh does not churn OS watcher handles.
    pub fn sync_roots(&self, scope: WatchScope, roots: impl IntoIterator<Item = PathBuf>) {
        let desired: HashSet<PathBuf> = roots
            .into_iter()
            .filter(|root| root.is_dir())
            .map(|root| dunce::canonicalize(&root).unwrap_or(root))
            .collect();

        let mut watchers = self.watchers.lock();
        watchers.retain(|(registered_scope, root), _| {
            *registered_scope != scope || desired.contains(root)
        });

        for root in desired {
            let key = (scope, root.clone());
            if watchers.contains_key(&key) {
                continue;
            }

            let changed_tx = self.changed_tx.clone();
            let internal_writes = self.internal_writes.clone();
            let result = RecommendedWatcher::new(
                move |event: notify::Result<Event>| match event {
                    Ok(event) if is_tree_change(&event) => {
                        let had_paths = !event.paths.is_empty();
                        let paths: Vec<PathBuf> = event
                            .paths
                            .into_iter()
                            .filter_map(|path| {
                                let normalized = dunce::canonicalize(&path).unwrap_or(path);
                                if is_recent_internal_write(&internal_writes, &normalized) {
                                    None
                                } else {
                                    Some(normalized)
                                }
                            })
                            .collect();
                        if !paths.is_empty() || !had_paths {
                            let _ = changed_tx.send(WatchChange { scope, paths });
                        }
                    }
                    Ok(_) => {}
                    Err(error) => {
                        // A watcher error can mean events were lost. Trigger a
                        // full discovery so the tree converges again.
                        tracing::warn!(
                            ?error,
                            ?scope,
                            "file-tree watcher error; requesting rescan"
                        );
                        let _ = changed_tx.send(WatchChange {
                            scope,
                            paths: Vec::new(),
                        });
                    }
                },
                Config::default(),
            )
            .and_then(|mut watcher| {
                watcher.watch(&root, RecursiveMode::Recursive)?;
                Ok(watcher)
            });

            match result {
                Ok(watcher) => {
                    watchers.insert(key, watcher);
                }
                Err(error) => {
                    tracing::warn!(?error, ?scope, path = %root.display(), "failed to watch file-tree root");
                }
            }
        }
    }
}

fn is_tree_change(event: &Event) -> bool {
    if event.need_rescan() {
        return true;
    }

    match event.kind {
        EventKind::Create(_) | EventKind::Remove(_) => true,
        EventKind::Modify(ModifyKind::Name(_) | ModifyKind::Any | ModifyKind::Other) => true,
        EventKind::Any | EventKind::Other => true,
        EventKind::Modify(ModifyKind::Data(_)) => true,
        EventKind::Access(_) | EventKind::Modify(ModifyKind::Metadata(_)) => false,
    }
}

fn is_recent_internal_write(
    writes: &parking_lot::Mutex<HashMap<PathBuf, Instant>>,
    path: &std::path::Path,
) -> bool {
    const INTERNAL_WRITE_WINDOW: Duration = Duration::from_secs(2);
    let mut writes = writes.lock();
    writes.retain(|_, at| at.elapsed() <= INTERNAL_WRITE_WINDOW);
    writes
        .get(path)
        .is_some_and(|at| at.elapsed() <= INTERNAL_WRITE_WINDOW)
}

fn dispatch_changes(app: AppHandle, changed_rx: Receiver<WatchChange>) {
    while let Ok(first) = changed_rx.recv() {
        let mut changes: HashMap<WatchScope, HashSet<PathBuf>> = HashMap::new();
        changes.entry(first.scope).or_default().extend(first.paths);
        let deadline = Instant::now() + DEBOUNCE_WINDOW;

        loop {
            let Some(remaining) = deadline.checked_duration_since(Instant::now()) else {
                break;
            };
            match changed_rx.recv_timeout(remaining) {
                Ok(change) => {
                    changes
                        .entry(change.scope)
                        .or_default()
                        .extend(change.paths);
                }
                Err(RecvTimeoutError::Timeout) => break,
                Err(RecvTimeoutError::Disconnected) => return,
            }
        }

        for (scope, paths) in changes {
            let paths = paths
                .into_iter()
                .map(|path| path.to_string_lossy().into_owned())
                .collect();
            if let Err(error) = app.emit(FILE_TREE_CHANGED_EVENT, FileTreeChanged { scope, paths })
            {
                tracing::warn!(?error, ?scope, "failed to emit file-tree change");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use notify::event::{AccessKind, CreateKind, DataChange};

    #[test]
    fn ignores_access_events_but_keeps_structural_changes() {
        let access = Event::new(EventKind::Access(AccessKind::Any));
        let create = Event::new(EventKind::Create(CreateKind::File));
        let content = Event::new(EventKind::Modify(ModifyKind::Data(DataChange::Content)));
        let unknown_data = Event::new(EventKind::Modify(ModifyKind::Data(DataChange::Any)));

        assert!(!is_tree_change(&access));
        assert!(is_tree_change(&create));
        assert!(is_tree_change(&content));
        assert!(is_tree_change(&unknown_data));
    }
}
